resources:
- name: aws-infrastructire
  type: git
  source:
    uri: https://github.com/sunckell/continuous-integration-delivery-demo
    branch: master

jobs:
- name: terraform plan
  plan:
  - get: continuous-integration-delivery-demo
    trigger: true
  - task: tests
    file: 
