resources:
- name: aws-images
  type: git
  source:
    uri: https://github.com/sunckell/continuous-integration-delivery-demo
    branch: master

jobs:
- name: iam role update
  plan:
  - get: 
    trigger: true
  - task: tests
    file: 
